language: c++

addons:
    apt:
        update: true

env:
    - DIR=IT1
    - DIR=IT2

before_install:
    - sudo apt update
    - sudo apt install valgrind
    - sudo apt install cmake
      # Установка gtest
    - sudo apt install libgtest-dev 
    - cd /usr/src/gtest 
    - make
    - sudo cp *.a /usr/lib

script:
    - cd $DIR
    - cmake CMakeLists.txt
    - make test
    - valgrind --leak-check=full -q ./test.exe

