addons:
    apt:
        update: true

env:
    global:
    - CODECOV_TOKEN="01abb78d-7b9d-4213-baec-4d51c880f9bc"
    jobs:
    - DIR=IT1
    - DIR=IT2

language: c++

before_install:
      # Идём в директорию IT1
    - cd IT1
    - sudo apt update
    - sudo apt install valgrind
    - sudo apt install cmake
      # Установка gtest
    - sudo apt install libgtest-dev 
    - cd /usr/src/gtest 
    - sudo cmake CMakeLists.txt || (cat CMakeFiles/CMakeError.log && CMakeFiles/CMakeOutput.log)
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

script:
    - cmake CMakeLists.txt
    - ls
    - make 
    - valgrind --leak-check=full -q ./run_tests.exe

after_script:
    - make clean


