addons:
  apt:
    update: true

os: linux
language: cpp

env:
  - DIR=IT1
  - DIR=IT2

stages:
  - install
  - cppcheck
  - build

stage: install
install:
  - sudo apt update
  - sudo apt install build-essential
  - sudo apt install valgrind
  - sudo apt install cmake
  # setup gtest
  - sudo apt install libgtest-dev 
  - cd /usr/src/gtest 
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  # build all 
  - cd $DIR
  - cmake .
  - cmake --build .

 script: skip


        
          #    stage: st3
          #        script:
          #         - valgrind --leak-check=full -q ./test.exe
          #         - cd CMakeFiles/test.exe.dir
          #         - echo "Покрытие:"
          #         - gcov test.cpp | head -n 2


