os: linux
language: cpp

env:
 - DIR=IT1

addons:
  apt:
    update: true
    packages:
      - cppcheck
      - valgrind
      - cmake
      - build-essential
      - libgtest-dev
      - lcov

before_scrit:
  # setup gtest
  - cd /usr/src/gtest 
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  - cd IT2
  - cmake .
  - cmake --build .

jobs:
  include:
    - stage: "lint"
      script: cppcheck -j4 --inconclusive --error-exitcode=1 .
     
    - stage: "unit_test"
      script:
      - ./test.exe

    - stage: "coverage"
      - lcov -d . -c -o coverage.info
      - lcov bash <(curl -s https://codecov.io/bash) -f coverage.info

