addons:
  apt:
    update: true

os: linux
language: cpp

stages:
  - lint
  - install
  - build
  - unit_tests
  - coverage
  - valgrind

jobs:
  include:
    - stage: lint
      before_install:
        - sudo apt install cppcheck
        - cppcheck ./IT2

    - stage: install
      install:
      - sudo apt update
      - sudo apt install build-essential
      - sudo apt install valgrind
      - sudo apt install cmake
        # setup gtest
      - sudo apt install libgtest-dev 
      - cd /usr/src/gtest 
      - sudo cmake .
      - sudo make
      - sudo cp *.a /usr/lib
      - cd -
 
    - stage: build
      before_script:
      - cd $DIR
      - cmake .
      - cmake --build .

    - stage: unit_tests
      ./test.exe
    - stage: coverage
      - cd CMakeFiles/test.exe.dir
      - echo "Покрытие:"
      - gcov test.cpp | head -n 2


    - valgrind: 

