os: linux
language: cpp

addons:
  apt:
    update: true
    packages:
      - cppcheck
      - valgrind
      - cmake
      - build-essential
      - libgtest-dev
      - lcov

before_install:
  # setup gtest
  - cd /usr/src/gtest 
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

before_script:
  - cd IT2
  - cmake .
  - cmake --build .

jobs:
  include:
    - stage: ci
      name: lint
      script: cppcheck -j4 --inconclusive --error-exitcode=1 .

      name: unit_tests
      script:
      - ./test.exe

      after_success:
      - lcov -d . -c -o coverage.info
      - lcov bash <(curl -s https://codecov.io/bash) -f coverage.info

