language: c++

addons:
    apt:
        update: true
        packages:
          - cppcheck
          - valgrind
          - cmake
          - libgtest-dev
          - lcov

env:
    - DIR=IT1
    - DIR=IT2

before_script:
      # Установка gtest
    - cd /usr/src/gtest 
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib

script:
    - cd -
    - cd $DIR
    - cmake CMakeLists.txt
    - make test.exe
      # Запуск тестов
    - valgrind --leak-check=full -q ./test.exe
      # Показ покрытия
    - cd CMakeFiles/test.exe.dir
    - echo "Покрытие:"
    - gcov test.cpp | head -n 2

