language: c++

before_install:
    - sudo apt update
    - sudo apt install valgrind
    - sudo apt install cmake

script:
    - make
    - valgrind --leak-check=full -q ./run_tests.exe

after_script:
    - make clean

