language: c++

before_install:
    - sudo apt update
    - sudo apt install valgrind
    - sudo apt install cmake
    - sudo apt install libgtest-dev

script:
    - cmake CMakeLists.txt
    - make Makefile
    - valgrind --leak-check=full -q ./run_tests.exe

after_script:
    - make clean

