language: c++

addons:
    apt:
        update: true

env:
    - DIR=IT1
    - DIR=IT2

before_install:
    - sudo apt update
    - sudo apt install build-essential
    - sudo apt install valgrind
    - sudo apt install cmake
      # Установка gtest
    - sudo apt install libgtest-dev 
    - cd /usr/src/gtest 
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib

script:
    - cd -
    - cd $DIR
    - cmake CMakeLists.txt
    - make test.exe
      # Запуск тестов
    - valgrind --leak-check=full -q ./test.exe
      # Показ покрытия
    - cd CMakeFiles/test.exe.dir
    - echo "Покрытие:"
    - gcov main.cpp | head -n 2

