
addons:
  apt:
    update: true

stages:
    - st1
    - st2
    - st3
    - st4

env:
  - DIR=IT1
  - DIR=IT2

language: cpp

jobs:
  include:
      stage: st1
      before_install:
      - sudo apt update
      - sudo apt install build-essential
      - sudo apt install valgrind
      - sudo apt install cmake
      stage: st2
        # Установка gtest
      - sudo apt install libgtest-dev 
      - cd /usr/src/gtest 
      - sudo cmake .
      - sudo make
      - sudo cp *.a /usr/lib
      - cd -

      stage: st3
      before_script:
      - cd $DIR
      - cmake CMakeLists.txt
      - make
      stage: st4
      - valgrind --leak-check=full -q ./test.exe
      - cd CMakeFiles/test.exe.dir
      - echo "Покрытие:"
      - gcov test.cpp | head -n 2

 
