addons:
  apt:
    update: true

os: linux
language: cpp

env: DIR=IT2

stages:
  - lint
  - build
  - unit_tests
  - coverage
  - valgrind

jobs:
  include:
    - stage: lint
      install:
        - sudo apt install cppcheck
      script:
        - cppcheck ./$DIR

    - stage: build
      install:
      - sudo apt update
      - sudo apt install build-essential
      - sudo apt install valgrind
      - sudo apt install cmake
        # setup gtest
      script:
      - sudo apt install libgtest-dev 
      - cd /usr/src/gtest 
      - sudo cmake .
      - sudo make
      - sudo cp *.a /usr/lib
      - cd -
      

    - stage: unit_tests
      script:
      - cd $DIR
      - cmake .
      - cmake --build .
      - ls
      - ./test.exe

    - stage: coverage
      script:
      - cd $DIR
      - cd CMakeFiles/test.exe.dir
      - echo "Покрытие:"
      - gcov test.cpp | head -n 2

      after_success: bash <(curl -s https://codecov.io/bash)

