language: c++

before_install:
    - sudo apt update
    - sudo apt install valgrind
    - sudo apt install cmake
      # Установка gtest
    - sudo apt install libgtest-dev 
    - cd /usr/src/gtest 
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

script:
    - cmake CMakeLists.txt
    - make Makefile
    - valgrind --leak-check=full -q ./run_tests.exe

after_script:
    - make clean

addons:
    apt:
        update: true

