# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/Learning/tech/c/IT_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/Learning/tech/c/IT_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Learning/tech/c/IT_1/CMakeFiles /home/arthur/Learning/tech/c/IT_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Learning/tech/c/IT_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runTests.exe

# Build rule for target.
runTests.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runTests.exe
.PHONY : runTests.exe

# fast build rule for target.
runTests.exe/fast:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/build
.PHONY : runTests.exe/fast

#=============================================================================
# Target rules for targets named app.exe

# Build rule for target.
app.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app.exe
.PHONY : app.exe

# fast build rule for target.
app.exe/fast:
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/build
.PHONY : app.exe/fast

io_tools.o: io_tools.c.o

.PHONY : io_tools.o

# target to build an object file
io_tools.c.o:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/io_tools.c.o
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/io_tools.c.o
.PHONY : io_tools.c.o

io_tools.i: io_tools.c.i

.PHONY : io_tools.i

# target to preprocess a source file
io_tools.c.i:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/io_tools.c.i
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/io_tools.c.i
.PHONY : io_tools.c.i

io_tools.s: io_tools.c.s

.PHONY : io_tools.s

# target to generate assembly for a file
io_tools.c.s:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/io_tools.c.s
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/io_tools.c.s
.PHONY : io_tools.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/main.c.s
.PHONY : main.c.s

proc_tools.o: proc_tools.c.o

.PHONY : proc_tools.o

# target to build an object file
proc_tools.c.o:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/proc_tools.c.o
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/proc_tools.c.o
.PHONY : proc_tools.c.o

proc_tools.i: proc_tools.c.i

.PHONY : proc_tools.i

# target to preprocess a source file
proc_tools.c.i:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/proc_tools.c.i
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/proc_tools.c.i
.PHONY : proc_tools.c.i

proc_tools.s: proc_tools.c.s

.PHONY : proc_tools.s

# target to generate assembly for a file
proc_tools.c.s:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/proc_tools.c.s
	$(MAKE) -f CMakeFiles/app.exe.dir/build.make CMakeFiles/app.exe.dir/proc_tools.c.s
.PHONY : proc_tools.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/runTests.exe.dir/build.make CMakeFiles/runTests.exe.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... runTests.exe"
	@echo "... rebuild_cache"
	@echo "... app.exe"
	@echo "... io_tools.o"
	@echo "... io_tools.i"
	@echo "... io_tools.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... proc_tools.o"
	@echo "... proc_tools.i"
	@echo "... proc_tools.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

